import type { ReactNode } from "react";
import { useTranslation } from "react-i18next";

/**
 * ChartCard — the dashboard atom for the quanti surface.
 *
 * Enforces three editorial rules from the design-system plan:
 *   1. Every chart has a takeaway sentence above it (the interpretive anchor).
 *   2. Every chart shows n + completion rate + CI in the footer.
 *   3. Below `minN`, the chart slot should switch to count display and we
 *      surface a small-n warning chip in the footer.
 *
 * Composition over configuration: the chart itself is `children`. ChartCard
 * is the frame; what's inside it is anything that paints — Recharts, SVG,
 * a table, etc. This keeps the editorial discipline portable across chart
 * libraries.
 */
interface ChartCardProps {
  /** Uppercase label above the takeaway, e.g. "LIKERT · Q3" */
  eyebrow?: string;
  /** Serif takeaway sentence — the interpretive anchor. Auto-generated by AI in production. */
  takeaway: string;
  /** Sample size — drives small-n warning when below `minN`. */
  n?: number;
  /** Completion rate as a 0–100 percentage. */
  completionRate?: number;
  /** Confidence interval half-width in percentage points (e.g. 5.4 for ±5.4pp). */
  ciHalfWidth?: number;
  /** Threshold below which a small-n warning is shown. Default 30 (segment-split rule). */
  minN?: number;
  /** Extra metadata items appended to the footer (e.g. fielding window). */
  footerExtras?: ReactNode[];
  children: ReactNode;
}

export function ChartCard({
  eyebrow,
  takeaway,
  n,
  completionRate,
  ciHalfWidth,
  minN = 30,
  footerExtras,
  children,
}: ChartCardProps) {
  const { t } = useTranslation("study");
  const showSmallN = typeof n === "number" && n < minN;
  const footerItems: ReactNode[] = [];

  if (typeof n === "number") footerItems.push(t("chartCard.n", { count: n }));
  if (typeof completionRate === "number") {
    footerItems.push(t("chartCard.completion", { count: Math.round(completionRate) }));
  }
  if (typeof ciHalfWidth === "number") {
    footerItems.push(t("chartCard.ci", { value: ciHalfWidth.toFixed(1) }));
  }
  if (footerExtras) footerItems.push(...footerExtras);

  return (
    <div className="chart-card">
      {eyebrow ? <div className="chart-card__eyebrow">{eyebrow}</div> : null}
      <p className="chart-card__takeaway">{takeaway}</p>
      <div className="chart-card__chart">{children}</div>
      {(footerItems.length > 0 || showSmallN) && (
        <div className="chart-card__footer">
          {footerItems.map((item, i) => (
            <span key={i} style={{ display: "inline-flex", alignItems: "center", gap: "var(--space-3)" }}>
              {item}
              {i < footerItems.length - 1 && <span className="chart-card__footer-divider">·</span>}
            </span>
          ))}
          {showSmallN && (
            <span className="chart-card__warning" title={t("chartCard.smallNTitle")}>
              {t("chartCard.smallNWarning", { minN })}
            </span>
          )}
        </div>
      )}
    </div>
  );
}
