"""Tests for the funnel analytics emitter and the concrete-recap helper.

Both are part of the Wave 1 activation-push work — analytics gives us
the cohort numbers; the recap is what makes the completion screen feel
earned.
"""

from __future__ import annotations

import logging
from types import SimpleNamespace

from app.models.company import Company
from app.routers.copilot import _build_profile_summary
from app.services.analytics import emit_event


class TestAnalyticsEmitter:
    def test_emits_structured_log_line(self, caplog):
        company = Company(
            id="c-1",
            name="Acme",
            email="alice@acme.com",
            first_name="Alice",
            role="Product Manager",
            company_size="11–50",
            industry="SaaS / Tech",
            use_case="Product discovery",
            subscription_tier="starter",
        )
        with caplog.at_level(logging.INFO):
            emit_event("signup", company=company, plan_requested="starter")
        records = [r for r in caplog.records if r.message.startswith("analytics ")]
        assert records, "no analytics line emitted"
        msg = records[-1].message
        assert "event=signup" in msg
        assert "company_id=c-1" in msg
        assert 'role="Product Manager"' in msg
        assert "plan_id=starter" in msg
        assert "plan_requested=starter" in msg

    def test_works_without_company(self, caplog):
        # Some events fire before a Company exists (e.g. anonymous funnel
        # markers). The emitter must not crash.
        with caplog.at_level(logging.INFO):
            emit_event("trial_paywall_hit", reason="participant_limit")
        records = [r for r in caplog.records if r.message.startswith("analytics ")]
        assert records
        assert "event=trial_paywall_hit" in records[-1].message
        assert "reason=participant_limit" in records[-1].message

    def test_never_raises_on_bad_input(self, caplog):
        # Pass a truly broken sentinel that .startswith would explode on.
        broken = SimpleNamespace()
        # Should not raise even though `broken` is missing every Company
        # attribute the emitter touches.
        with caplog.at_level(logging.INFO):
            emit_event("study_created", company=broken)  # type: ignore[arg-type]
        # No assertion needed — the contract is "never raise".


class TestProfileSummary:
    """Wave A Fix 1b — recap is now generated by Claude Haiku and
    cached on ``Company.onboarding_recap``. With no ANTHROPIC_API_KEY
    (test env), the Haiku path short-circuits and we fall back to the
    deterministic mini-recap.
    """

    def test_uses_cached_recap_when_present(self, db_session):
        company = Company(
            id="c-2-cached",
            email="cached@example.com",
            name="Cached",
            role="UX Researcher",
            onboarding_recap="Cached recap — should be returned verbatim.",
        )
        summary = _build_profile_summary(db_session, company)
        assert summary == "Cached recap — should be returned verbatim."

    def test_returns_empty_when_nothing_captured(self, db_session):
        company = Company(id="c-3", email="x@example.com", name="X")
        assert _build_profile_summary(db_session, company) == ""

    def test_fallback_recap_includes_role_when_no_api_key(self, db_session):
        # No ANTHROPIC_API_KEY in test env → Haiku path returns "" and
        # we fall back to the deterministic line.
        company = Company(
            id="c-4-fallback",
            email="y@example.com",
            name="Y",
            role="PM",
            company_size="11–50",
            industry="SaaS",
        )
        summary = _build_profile_summary(db_session, company)
        assert "PM" in summary
        # Cache write happened — subsequent calls return verbatim.
        assert company.onboarding_recap == summary

    def test_fallback_skips_literal_other_role(self, db_session):
        company = Company(
            id="c-5-other",
            email="other@example.com",
            name="O",
            role="Other",
            company_size="11–50",
            industry="SaaS",
        )
        summary = _build_profile_summary(db_session, company)
        # The literal "Other" must NOT appear as the role label.
        assert "Other" not in summary
        # Other fields still surface so the recap isn't empty.
        assert "11–50" in summary or "SaaS" in summary


class TestFirstResponseEmail:
    """W3.2 — the lifecycle email that pulls the researcher back at the
    moment their first response arrives. Fires once per workspace,
    idempotent via Company.first_response_email_sent_at."""

    def test_template_renders_subject_and_body(self):
        from app.services.email import send_first_response_in
        from unittest.mock import patch

        with patch("app.services.email.send_email", return_value=True) as mock:
            ok = send_first_response_in(
                to="alice@acme.com",
                project_name="Trial drop-off study",
                project_url="https://app.qualipulse.com/projects/p-1?tab=responses",
                lang="en",
            )
        assert ok is True
        kwargs = mock.call_args.kwargs
        assert kwargs["to"] == "alice@acme.com"
        assert "Trial drop-off study" in kwargs["subject"]
        assert "first response" in kwargs["subject"].lower()
        assert "Listen to the response" in kwargs["body_html"]
        assert "Trial drop-off study" in kwargs["body_html"]

    def test_template_renders_french(self):
        from app.services.email import send_first_response_in
        from unittest.mock import patch

        with patch("app.services.email.send_email", return_value=True) as mock:
            send_first_response_in(
                to="x@x.com",
                project_name="Étude pilote",
                project_url="https://example.com",
                lang="fr",
            )
        body = mock.call_args.kwargs["body_html"]
        assert "Écouter la réponse" in body
        assert "Étude pilote" in body
