"""English participant transcripts for the onboarding demo project. Auto-generated fixture content."""

PARTICIPANTS_EN = [
    {
        "display_name": "Sarah K.",
        "email": "sarah.demo@example.com",
        "profession": "Engineering Lead",
        "age_range": "40-49",
        "country": "Germany",
        "language": "en",
        "turns": [
            {
                "question_index": 1,
                "is_follow_up": False,
                "question_text": "Walk me through a typical work day. When are you working solo and when are you collaborating with your team?",
                "response_transcript": "Okay, so my day is actually quite structured, because I learned the hard way that it has to be. I start around 8:30, and the first two hours are mine. No Slack, no meetings, nothing. I review pull requests, I think about architecture, I write the hard email I didn't want to write yesterday. Then from 10:30 until roughly 13:00 I overlap with Bangalore, that's when we do stand-ups, pairing sessions, the technical calls. After lunch I go into what I call the European block, one-on-ones with my team here in Berlin, planning, the usual. And I try, I really try, to be offline by 18:00. I don't always manage it, but that's the shape of it. Process is process, yeah?",
            },
            {
                "question_index": 1,
                "is_follow_up": True,
                "question_text": "How did you actually enforce that morning block? Most leads I talk to say they can't.",
                "response_transcript": "Honestly? I had to be a bit rude about it at first. I turned off notifications, I set my Slack status to \"deep work, back at 10:30\" and I just didn't respond. The first week people were a bit, you know, confused. Someone messaged me \"are you okay?\" because I hadn't answered for 90 minutes. And I realised, that's the problem right there, that's the thing we need to fix. I had to model it. I wrote about it in our team channel, I said look, I'm doing this, I expect you to do it too, I will not message you before 10:30 unless production is literally on fire. And slowly, slowly, it became normal. But the social cost at the beginning was real, I won't lie about that.",
            },
            {
                "question_index": 2,
                "is_follow_up": False,
                "question_text": "What tools do you use to stay in sync with your team, and how did your tool stack evolve to look the way it does today?",
                "response_transcript": "We use Linear for tracking, Slack for chat obviously, GitHub for code, Notion for documentation, and Loom for async video. Five tools, which already I think is too many. We came from Jira and I hated Jira, I really did, it's a tool with no opinion, you can configure it to do anything and that means every team uses it differently and nothing is consistent. Linear has opinions, and I like tools that have opinions, it tells you how to work. The problem now is not the tools themselves, the problem is the integration between them. A decision happens in Slack, the ticket is in Linear, the actual discussion is in a GitHub PR, and the context is in a Notion doc from six months ago. Good luck finding anything.",
            },
            {
                "question_index": 2,
                "is_follow_up": True,
                "question_text": "When you say decisions disappear in Slack, can you give me a concrete example?",
                "response_transcript": "Yeah, so just last month, we had a discussion about whether to migrate one of our services off a certain database. It was a good discussion, maybe forty messages, three engineers, lots of trade-offs. We decided to wait six months. Fine. Two weeks ago, a new engineer on the team asks in another channel, hey should we migrate this service? And nobody remembered the previous discussion. I had to scroll back, find it, screenshot it, paste it. The decision existed, it just wasn't anywhere you could find it. That's a pattern, that's not a one-off. I would say maybe once a week I'm archaeologist for my own team's past decisions. It's ridiculous when you say it out loud.",
            },
            {
                "question_index": 3,
                "is_follow_up": False,
                "question_text": "Tell me about a recent moment when you felt blocked or frustrated trying to work with your team. What happened?",
                "response_transcript": "Okay, two weeks ago. I'm reviewing a pull request from one of the engineers in Bangalore, and I have a question about why they chose a certain approach. I leave a comment. No answer. Because of course, they're asleep. So I wait. Next day, they answer, but their answer doesn't quite address what I asked, so I clarify. They're asleep again. This goes on for three working days for what should have been a fifteen-minute conversation. Three days. And I'm sitting here thinking, we could have solved this in one Zoom call. But the culture is very \"async is better, async is mature,\" and sometimes I want to say, no, sometimes a phone call is better. Sometimes you just need to talk to a human for twenty minutes.",
            },
            {
                "question_index": 4,
                "is_follow_up": False,
                "question_text": "When you need something from a teammate in a different time zone, what's your playbook?",
                "response_transcript": "So I've actually become quite disciplined about this, and I think the time zone thing, as annoying as it is, has forced us to be better. Before I message anyone in Bangalore, I ask myself: does this need a conversation, or do I just need an answer? If it's an answer, I write it as a Loom, three minutes max, with the context, the question, and what I'll do with their response. They wake up, watch it, reply in writing or with their own Loom, done. If it needs a conversation, I book a slot in the overlap window, 11:00 to 12:30 their time. No exceptions. And the funny thing is, this discipline, it would actually help teams in the same office. We just never need it there, so we never build it.",
            },
            {
                "question_index": 4,
                "is_follow_up": True,
                "question_text": "That's interesting. You're saying distance made you more intentional?",
                "response_transcript": "Exactly, yes. When everyone is in the same room, you can just tap someone on the shoulder, and so you do, constantly, and nobody protects their time because they can't. When you have a nine-hour gap, you have to think before you interrupt someone, because if you get it wrong you've lost a full day. So you get better at writing the question. You get better at anticipating what they'll ask back. You become, you know, more considered. I genuinely believe my Berlin team has worse async habits than my Bangalore colleagues, because the Berlin team never had to learn. They just shout across the office. And that's a kind of luxury that actually makes you worse at your job.",
            },
            {
                "question_index": 5,
                "is_follow_up": False,
                "question_text": "If you could wave a magic wand and fix one thing about how your team works together, what would it be and why?",
                "response_transcript": "One thing? Okay. I would make every decision automatically have a home. Not a person to write it up later, not a retro, not a \"someone should document this.\" I mean, the moment you decide something, it lands in a structured place where anyone can find it six months later with one search. Because right now, the knowledge of my team lives in my head and in two or three other senior engineers' heads, and when someone leaves, a piece of the company's memory just walks out the door. That is not acceptable, but we all pretend it is. Tools have not solved this. Notion, Confluence, whatever, they all fail in the same way, which is that documentation is a task, not a byproduct.",
            },
            {
                "question_index": 5,
                "is_follow_up": True,
                "question_text": "Why do you think documentation-as-a-task always fails?",
                "response_transcript": "Because humans don't want to do it. It's that simple. After a two-hour discussion you are tired, you want a coffee, you want to close your laptop, you do not want to open a fresh doc and write up what was just decided and why. Nobody does. So it gets skipped, or it gets done badly, or it gets done three weeks later by the person who has the least context. The only way this gets solved, in my opinion, is if the tool captures the decision at the moment it happens, from the actual conversation, without anyone having to think about it. I don't know if that's possible, but that's what I would want. Everything else we've tried has failed. Process is process, but only if the process is invisible.",
            },
        ],
    },
    {
        "display_name": "Ben R.",
        "email": "ben.demo@example.com",
        "profession": "Freelance Backend Developer",
        "age_range": "30-39",
        "country": "United Kingdom",
        "language": "en",
        "turns": [
            {
                "question_index": 1,
                "is_follow_up": False,
                "question_text": "Walk me through a typical work day. When are you working solo and when are you collaborating with your team?",
                "response_transcript": "Right, so I should probably explain, I work with three clients at any given time, so I don't really have one team, I have three. I go to a co-working space near London Bridge most days, because after lockdown I discovered that working from my flat was, yeah, let's say not great for my mental health. Mornings I tend to do focused coding, one client at a time, in blocks. Afternoons are when the meetings happen, usually two or three, spread across the clients. And then in the evening I sometimes pick up again if something's urgent, although I'm trying to stop doing that. The interesting thing, honestly, is that from the outside I see the same patterns across all three teams, and they all think their problems are unique. They're really, really not.",
            },
            {
                "question_index": 1,
                "is_follow_up": True,
                "question_text": "What patterns do you mean?",
                "response_transcript": "Oh, all sorts. They all think they have too many meetings. They all have a Slack channel that's basically a graveyard of half-finished conversations. They all have a Notion or a Confluence that nobody reads. They all have one person, usually a senior engineer, who holds the whole system in their head, and everyone quietly panics when that person goes on holiday. It's almost comforting, in a dark way, because when a client tells me \"we have a bit of a mess here\" I can honestly say, yeah, so does everyone else. You're not broken, you're just normal. Which isn't necessarily reassuring, I suppose, but it's accurate.",
            },
            {
                "question_index": 2,
                "is_follow_up": False,
                "question_text": "What tools do you use to stay in sync with your team, and how did your tool stack evolve to look the way it does today?",
                "response_transcript": "Well, I don't get to pick, that's the thing, each client has their own stack and I just adapt. Client A is Slack and Jira and Google Docs. Client B is Teams and Azure DevOps and SharePoint, which is, you know, a particular kind of experience. Client C is the modern one, Slack and Linear and Notion. And I live in all three simultaneously. I have three laptops, actually. Not because I need three laptops technically, but because context-switching between the tool stacks is so painful that physical separation helps. I think the honest answer to \"how did your stack evolve\" is, it didn't, really. Someone chose it five years ago, and now everyone's stuck with it, and nobody has the political capital to change it. That's most companies, in my experience.",
            },
            {
                "question_index": 2,
                "is_follow_up": True,
                "question_text": "You said no one has the political capital to change a tool stack. Why is that?",
                "response_transcript": "Because changing a tool is a six-month project that nobody wants to own. You've got to migrate data, you've got to retrain people, half the team will complain for weeks, and the person who championed it gets blamed every time something breaks. And the benefit, realistically, is, what, twenty percent less friction? It's not a career-making move, it's a career-ending move if you get it wrong. So people just, you know, they keep their heads down and they put up with Jira for another year, and another year, and another. I've watched this happen at, I think, every single client I've worked with. The tools don't get better because the cost of switching is higher than the cost of suffering. That's the whole story, honestly.",
            },
            {
                "question_index": 3,
                "is_follow_up": False,
                "question_text": "Tell me about a recent moment when you felt blocked or frustrated trying to work with your team. What happened?",
                "response_transcript": "Last week, actually. Client C, the modern one. I needed to know whether a particular API contract had been finalised, because I was about to build against it. I asked in Slack. Three different people replied with three different answers. One said yes, one said no, one said \"I think we talked about this in the Tuesday meeting.\" I checked the Tuesday meeting notes, nothing. I checked Linear, nothing. I checked Notion, there's a page but it's from two months ago and clearly out of date. So I just sat there for about forty minutes, not coding, just trying to figure out what was actually true. And in the end I had to book a fifteen-minute call with the tech lead to get a definitive answer. Forty minutes of my time, for information that should have taken ten seconds to look up. Bit silly, really.",
            },
            {
                "question_index": 3,
                "is_follow_up": True,
                "question_text": "Does it frustrate you more because you're an outsider? Or is that actually an advantage?",
                "response_transcript": "Honestly, it's both. It frustrates me more because I don't have the tribal knowledge, I can't ask \"Sam\" because I don't know who Sam is, I don't know whose opinion to trust. But it's also an advantage because I notice. The people on the inside, they've just, they've stopped seeing it. They've built workarounds, they know that if you want the real answer you DM Priya on Slack, and they don't even think about it anymore. I come in fresh every few months and I go, hang on, this is mad. Why are you all doing this? And sometimes they look at me like I've said something profound, when actually I've just, you know, pointed at the elephant.",
            },
            {
                "question_index": 4,
                "is_follow_up": False,
                "question_text": "When you need something from a teammate in a different time zone, what's your playbook?",
                "response_transcript": "I don't really have a playbook, which is probably my problem. Most of my clients are UK-based so it's not a huge issue, but one of them has a team in New York, five hours behind, and I'll be honest, I mostly just wait. I queue up my questions, I send them in a batch at the end of my day, and then I pick up again the next morning. It's not sophisticated. I've tried Loom a couple of times, and it works, it genuinely does, but I feel a bit self-conscious recording myself. I don't love the sound of my own voice. So I tend to default to very long, very detailed Slack messages with screenshots, which is probably slower and worse. I know I should do Loom more. I just don't.",
            },
            {
                "question_index": 5,
                "is_follow_up": False,
                "question_text": "If you could wave a magic wand and fix one thing about how your team works together, what would it be and why?",
                "response_transcript": "I'd fix the integration problem. Not consolidation, not \"let's all move to one tool,\" because that never works, you can see it doesn't. I'd fix the fact that the tools don't talk to each other properly. Every company I work with has seven or eight tools and they all sort of pretend to integrate, and the integrations are always the cheapest, most half-hearted version. A Slack message should know it's about a Linear ticket. A Linear ticket should know which GitHub PR is attached. A Notion doc should know when the thing it describes has changed. None of this is hard, technically, but nobody's done it properly, and so we all just live with this, you know, this low-level papercut all day, every day. And we accept it, which is the maddest part.",
            },
            {
                "question_index": 5,
                "is_follow_up": True,
                "question_text": "Why do you think nobody has solved it, if it's not technically hard?",
                "response_transcript": "Because the incentives aren't there, really. Each tool wants to be the one you live in. Slack doesn't want you leaving Slack. Linear doesn't want you leaving Linear. So their integrations with each other are deliberately, you know, just good enough to tick a box on the marketing page, but not good enough to actually work. And the customer, which is us, we've been trained to expect this, so we don't even complain. It's like, imagine if your phone couldn't properly copy text from one app to another. You'd lose your mind. But with work tools we've just accepted it. Someone will eventually do it right and make an enormous amount of money, I think, and the rest of us will look back and go, why did we put up with that for so long?",
            },
        ],
    },
    {
        "display_name": "James T.",
        "email": "james.demo@example.com",
        "profession": "Founder and CEO",
        "age_range": "40-49",
        "country": "United States",
        "language": "en",
        "turns": [
            {
                "question_index": 1,
                "is_follow_up": False,
                "question_text": "Walk me through a typical work day. When are you working solo and when are you collaborating with your team?",
                "response_transcript": "Yeah, so, my day is, honestly, it's mostly other people. I wish it weren't, but it is. I'm up around six, I do email and Slack catch-up for an hour because my team in Poland has been working since about 8 AM their time. By 8 my calendar starts, and I'll do five, six, sometimes seven meetings in a day. I try to block off an hour in the afternoon for what I call \"CEO thinking time,\" you know, strategy, the bigger questions, but I will tell you honestly, that block gets eaten probably four days out of five. Something comes up, someone needs a decision, a customer call runs long. And then in the evening, after my kids go to bed, that's when I actually do focused work. Which I know, I know, is not sustainable. I'm aware.",
            },
            {
                "question_index": 1,
                "is_follow_up": True,
                "question_text": "Why do you think the afternoon block keeps getting eaten?",
                "response_transcript": "Because I let it. That's the real answer. I could say no, I could tell people to go figure it out, I could hold the line. But I don't, because a part of me, honestly, feels guilty saying no, and another part of me kind of likes being needed. That's the thing I don't think founders say out loud enough. The availability thing, it's not just a scheduling problem, it's an ego problem. If my team figures out how to ship without me for two hours, what does that say about me? Nothing bad, obviously, that's exactly what a healthy team should do. But in the moment, when someone Slacks me with a question, the dopamine hit of being helpful wins over the discipline of being strategic. Every time. Almost every time.",
            },
            {
                "question_index": 2,
                "is_follow_up": False,
                "question_text": "What tools do you use to stay in sync with your team, and how did your tool stack evolve to look the way it does today?",
                "response_transcript": "We're a Slack, Linear, Notion, GitHub shop. Pretty standard for our size, which is twenty-five people. We started on Jira because I'd used it at my last job and I knew it, and we migrated to Linear about eighteen months ago because the engineers basically staged, like, a very polite rebellion. They said, look, this is slowing us down, we want to try Linear, and I said fine. That was one of the best decisions we made. Notion came in for docs, Loom came in for async demos. Every new tool we added solved a real problem, but the total experience of, you know, trying to find a thing, has gotten worse every quarter. More tools, more places to look, more places for things to get lost. That's the irony of it.",
            },
            {
                "question_index": 3,
                "is_follow_up": False,
                "question_text": "Tell me about a recent moment when you felt blocked or frustrated trying to work with your team. What happened?",
                "response_transcript": "Okay, so, a couple weeks ago, we had a board meeting coming up, and I wanted to pull together a slide on our pricing changes from Q3. I remembered we'd had a big discussion about it, I remembered the shape of the outcome, but I could not find where the decision lived. I looked in Notion, I found an old draft from before the decision. I looked in Linear, I found the ticket but no conclusion. I looked in Slack, I found the thread but it was forty messages and the resolution was in a DM I wasn't part of. I ended up, no joke, I ended up just messaging the three people who were in the discussion and asking them to tell me what we'd decided. As the CEO. About my own company. It was humbling and a little depressing.",
            },
            {
                "question_index": 3,
                "is_follow_up": True,
                "question_text": "Have you tried to systematically fix this?",
                "response_transcript": "I've tried, yeah. I've tried three or four times. I've announced it in all-hands, I've said we're going to write decision docs, we're going to tag them in Notion, we're going to have a decision log. Every time, it works for about two weeks and then it quietly dies. And the thing I've come to realize, and this is painful, is that announcing a process doesn't change anything. Nothing. You can say it in every all-hands from now until retirement, people will nod, and then they'll go back to doing what they did before. The only thing that actually changes behavior is when the leaders model it, consistently, over months. And I'm not good at consistency. I'm good at starting. Finishing is harder.",
            },
            {
                "question_index": 4,
                "is_follow_up": False,
                "question_text": "When you need something from a teammate in a different time zone, what's your playbook?",
                "response_transcript": "My team in Poland is six hours ahead, so we have this narrow overlap window from about 9 to 11 my time, 3 to 5 theirs. That's when we do real-time stuff. Outside of that, honestly, my playbook is mostly Loom. I record a three-minute video, I dump the context, I ask the question, I hit send. And then I try, try, to not check for the answer for at least a few hours because otherwise I'm just sitting there refreshing Slack like a kid waiting for a text back. The thing I've gotten better at, slowly, is writing the question properly the first time. Early on I'd ask something vague and then we'd lose a day on clarification. Now I over-specify. Way too much context is better than not enough when the round trip is twelve hours.",
            },
            {
                "question_index": 4,
                "is_follow_up": True,
                "question_text": "You mentioned you're part of the availability problem. How does that show up with the Poland team?",
                "response_transcript": "Oh, it's terrible. I'll message them at, like, 10 PM my time, which is 4 AM their time, because I just had an idea and I wanted to get it out of my head. And I'll write \"no rush, whenever\" at the bottom, which is, you know, that's the lie we all tell. Because they wake up, they see a message from the CEO, and of course they feel pressure to respond fast, no matter what I wrote. I know this. I have been told this explicitly by my team. And I still do it, which, again, is the gap between what I know and what I do. I've tried the scheduled send feature and I forget. I've tried writing drafts in Notion instead and I forget. The only thing that works is not having the idea at 10 PM, and I can't control that.",
            },
            {
                "question_index": 5,
                "is_follow_up": False,
                "question_text": "If you could wave a magic wand and fix one thing about how your team works together, what would it be and why?",
                "response_transcript": "I would fix the gap between what leaders say and what leaders do. That's the one. Culture doesn't come from all-hands speeches, it doesn't come from values posted on the wall, it doesn't come from a Notion page about \"how we work.\" It comes from what the founder and the senior leaders actually, physically do, every day, in front of everyone. If I say we value focus time but I send messages at 10 PM, the real message is, focus time is optional. If I say we document decisions but I don't document mine, the real message is, documentation is for other people. I know this. I say it to other founders. And I still fall into the trap constantly. The gap between knowing and doing, in leadership, is basically the whole game. And I haven't figured it out yet.",
            },
            {
                "question_index": 5,
                "is_follow_up": True,
                "question_text": "If you're so aware of it, what's stopping you from just doing it differently tomorrow?",
                "response_transcript": "Honestly? Fear, partly. And habit, mostly. I've been running this company for seven years, and the habits I built when we were five people, they don't scale, but they're the habits that got us here, so there's this voice that says, don't mess with what worked. The other thing is, I genuinely don't know what to replace them with. Everyone talks about async-first and documented decisions and protected focus time, and I believe in all of it, intellectually, but then Monday morning comes and I just, I revert. I fall back into meetings and Slack and reacting. I think what I actually need is not another framework, I need something, or someone, holding up a mirror, going, hey, you just did the thing again. Without that, I don't think I change.",
            },
        ],
    },
]

NOTABLE_QUOTES_EN = [
    {
        "participant_index": 0,
        "turn_index": 3,
        "text": "maybe once a week I'm archaeologist for my own team's past decisions",
        "theme_hint": "decision_capture",
    },
    {
        "participant_index": 0,
        "turn_index": 6,
        "text": "When everyone is in the same room, you can just tap someone on the shoulder, and so you do, constantly, and nobody protects their time",
        "theme_hint": "cross_timezone_health",
    },
    {
        "participant_index": 0,
        "turn_index": 7,
        "text": "documentation is a task, not a byproduct",
        "theme_hint": "decision_capture",
    },
    {
        "participant_index": 1,
        "turn_index": 7,
        "text": "Every company I work with has seven or eight tools and they all sort of pretend to integrate",
        "theme_hint": "tool_sprawl",
    },
    {
        "participant_index": 1,
        "turn_index": 1,
        "text": "one person, usually a senior engineer, who holds the whole system in their head, and everyone quietly panics when that person goes on holiday",
        "theme_hint": "decision_capture",
    },
    {
        "participant_index": 2,
        "turn_index": 4,
        "text": "announcing a process doesn't change anything. Nothing.",
        "theme_hint": "modelled_behaviour",
    },
    {
        "participant_index": 2,
        "turn_index": 7,
        "text": "The gap between knowing and doing, in leadership, is basically the whole game",
        "theme_hint": "modelled_behaviour",
    },
]
