"""Add participants.key_takeaways + notable_quotes (interview digest).

Per-interview digest generated by the same auto-run Claude pass as the
quality assessment: 3-5 key takeaways and up to 3 verbatim quotes, shown
in the transcript sidebar so a researcher opening a fresh interview gets
an instant read without waiting for the project-level analysis.

Revision ID: 0057_interview_digest
Revises: 0056_link_participant_cap
Create Date: 2026-08-10
"""
from alembic import op
import sqlalchemy as sa

revision = "0057_interview_digest"
down_revision = "0056_link_participant_cap"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column("participants", sa.Column("key_takeaways", sa.Text(), nullable=True))
    op.add_column("participants", sa.Column("notable_quotes", sa.Text(), nullable=True))


def downgrade() -> None:
    op.drop_column("participants", "notable_quotes")
    op.drop_column("participants", "key_takeaways")
